### ISSUE TITLE
Catégorie énergétique

### ISSUE THREAD

**Issue by goRaspy** [cmey/scrape-leboncoin-real-estate#4]
Hello je cherche à trier les annonces en fonction de la catégorie énergétique (impossible de filtrer sur lbc).

Est il possible de la scraper avec ce code ?

**Comment by cmey** [comment]
Non pas directement

car je ne scrape que les listings: https://www.leboncoin.fr/locations/offres, et pas les details de chaque annonce

tu peux forker et modifier mon code pour essayer de scraper les détails des annonces si tu veux
